# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tiago Moretto
email: moretto.tiago@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Meu Blog com Jekyll
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tiagomoretto.com.br" # the base hostname & protocol for your site
twitter_username: tmoretto
github_username:  tmoretto

# Build settings
markdown: kramdown
#permalink: /:categories/:year/:month/:day/:title
permalink: /:title